# Generated by Django 4.2.14 on 2024-07-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='Open', max_length=50),
        ),
    ]
